# Generated by Django 5.1.6 on 2025-02-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_userprofile_bio_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('applicant', 'Job Applicant')], default='applicant', max_length=10),
        ),
    ]
