# Generated by Django 5.1.6 on 2025-03-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('applicant', 'applicant')], default='applicant', max_length=10),
        ),
    ]
